aasd

diff --git a/.github/workflows/update-hlem.yaml b/.github/workflows/update-hlem.yaml
--- a/.github/workflows/update-hlem.yaml
+++ b/.github/workflows/update-hlem.yaml
@@ -36,27 +36,51 @@ jobs:
         ls -la  # list files to debug
 
     - name: Update Helm Chart Values
-      run: | 
+      run: |
         # Replace the value of 'tag' in your values.yaml file with the image tag
         if [ "${{ github.event.inputs.environment }}" == "dev" ]; then
-          sed -i "s/tag: .*/tag: ${{ github.event.inputs.tag }}/g" values-dev.yaml
+          sed -i "s/tag: .*/tag: ${{ github.event.inputs.tag }}/g" ${{ github.event.inputs.project_name }}-helm/values-dev.yaml
+          export UPDATED_VALUES_FILE="${{ github.event.inputs.project_name }}-helm/values-dev.yaml"
         elif [ "${{ github.event.inputs.environment }}" == "prod" ]; then
-          sed -i "s/tag: .*/tag: ${{ github.event.inputs.tag }}/g" values-prod.yaml
-        else
-          echo "Invalid environment specified"
-          exit 1
+          sed -i "s/tag: .*/tag: ${{ github.event.inputs.tag }}/g" ${{ github.event.inputs.project_name }}-helm/values-prod.yaml
+          export UPDATED_VALUES_FILE="${{ github.event.inputs.project_name }}-helm/values-prod.yaml"
         fi
-      working-directory: ${{ github.workspace }}/${{ github.event.inputs.project_name }}-helm
-
-    - name: Commit and Push Updated Values File
-      run: |
-        git config --global user.email "actions@github.com"
-        git config --global user.name "GitHub Actions"
-        git add values-*.yaml
-        git commit -m "Update image tag to ${{ github.event.inputs.tag }} for ${{ github.event.inputs.project_name }}"
-        git push
+      working-directory: ${{ github.workspace }}
       env:
-        GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
+        UPDATED_VALUES_FILE: ${{ env.UPDATED_VALUES_FILE }}
+
+      - name: Commit and Push Updated Values File
+        run: |
+          git config --global user.email "actions@github.com"
+          git config --global user.name "GitHub Actions"
+          git add ${{ env.UPDATED_VALUES_FILE }}
+          git diff --cached --exit-code || git commit -m "Update image tag to ${{ github.event.inputs.tag }} for ${{ github.event.inputs.project_name }} [skip ci]"
+          git push
+        env:
+          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
+
+    # - name: Update Helm Chart Values
+    #   run: | 
+    #     # Replace the value of 'tag' in your values.yaml file with the image tag
+    #     if [ "${{ github.event.inputs.environment }}" == "dev" ]; then
+    #       sed -i "s/tag: .*/tag: ${{ github.event.inputs.tag }}/g" values-dev.yaml
+    #     elif [ "${{ github.event.inputs.environment }}" == "prod" ]; then
+    #       sed -i "s/tag: .*/tag: ${{ github.event.inputs.tag }}/g" values-prod.yaml
+    #     else
+    #       echo "Invalid environment specified"
+    #       exit 1
+    #     fi
+    #   working-directory: ${{ github.workspace }}/${{ github.event.inputs.project_name }}-helm
+
+    # - name: Commit and Push Updated Values File
+    #   run: |
+    #     git config --global user.email "actions@github.com"
+    #     git config --global user.name "GitHub Actions"
+    #     git add values-*.yaml
+    #     git commit -m "Update image tag to ${{ github.event.inputs.tag }} for ${{ github.event.inputs.project_name }}"
+    #     git push
+    #   env:
+    #     GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
 
 
 
